env:
  MIX_ENV: test

name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Testing"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 22.2.6
          elixir-version: 1.12.0
      - run: mix deps.get
      - run: mix test
  heroku-deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 22.2.6
          elixir-version: 1.12.0
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: 'utrust-txpay' #Must be unique in Heroku
          heroku_email: 'paulofabiano@gmail.com'
